Adding coffee
hs3city/orpheus pull request #7
Opened 2021-01-12 17:09 UTC by nikisaku

In lines 50-54 addedd coffee job, but still have to fix calling it in line 69.

2021-01-13 10:02 UTC, DoomHammer requested changes

2021-01-13 10:02 UTC, DoomHammer commented on bot.py
> +@aiocron.crontab('45 10 * * 3,5')
`3,5`? Nie `2,4`?

2021-01-13 10:02 UTC, DoomHammer commented on bot.py
> +    datetime.date.today().strftime('%Y-%m-%d')
Po co nam to?

2021-01-13 10:02 UTC, DoomHammer commented on bot.py
> +        await client.get_channel(channel_id).send("Za kwadrans kawka na głosowym! ☕")
Odpali się to o 10:45 GMT, więc czasem faktycznie będzie za kwadrans, czasami nie.

Plus: w samo południe też warto powtórzyć wiadomość.

Plus: warto dodać że na kanale Relaks.

2021-01-13 11:05 UTC, nikisaku commented on bot.py
> +@aiocron.crontab('45 10 * * 3,5')
Tydzień liczy się od niedzieli (amerykański kalendarz), stąd 3 i 5.

2021-01-13 11:24 UTC, nikisaku commented on bot.py
> +        await client.get_channel(channel_id).send("Za kwadrans kawka na głosowym! ☕")
O 10:45 GMT zawsze będzie za kwadrans, jeżeli mamy kawę o 12:00 GMT +1, takie założenie przyjąłem. Chyba, że coś zgubiłem. :D
Dodałem informację o kanale relaks:
```
@aiocron.crontab('45 10 * * 3,5')
async def cronjob3():
    for channel in events_channel_ids:
        await client.get_channel(channel_id).send("Za kwadrans kawka na kanale głosowym Relaks! ☕")
```

Dodałem pracę, która ma to powtórzyć w południe:
```
@aiocron.crontab('0 11 * * 3,5')
async def cronjob4():
    for channel_id in channel_ids:
        await client.get_channel(channel_id).send("Zapraszamy na kawę na kanał głosowym Relaks! ☕")
```

2021-01-13 11:24 UTC, nikisaku commented on bot.py
> +    datetime.date.today().strftime('%Y-%m-%d')
W sensie? Całość, wydawało mi się, że definiuje pracę do zrobienia.
datetime chyba faktycznie bez sensu, wyciąłem.

2021-01-13 11:25 UTC, nikisaku commented on bot.py
> +    for channel_id in channel_ids:
A nie for `channel_id in events_channel_ids:`?

2021-01-13 11:30 UTC, nikisaku commented on bot.py
> +                    await cronjob3()
Poprawione, dziękuję!

2021-01-13 17:23 UTC, DoomHammer commented on bot.py
> +@aiocron.crontab('45 10 * * 3,5')
Sprawdzałeś? :>

2021-01-13 17:23 UTC, DoomHammer commented on bot.py
> +    for channel_id in channel_ids:
słusznie!

2021-01-13 17:44 UTC, nikisaku commented on bot.py
> +    for channel_id in channel_ids:
<3

2021-01-13 17:48 UTC, nikisaku commented on bot.py
> +@aiocron.crontab('45 10 * * 3,5')
Durny jak but, pamiętałem, że start od niedzieli, ale już nie, że od 0. Już poprawiam. :D

2021-01-13 17:59 UTC, DoomHammer commented on bot.py
> +@aiocron.crontab('45 10 * * 3,5')
Skoro robisz off-by-one to znaczy że jesteś prawdziwym koderem!

2021-02-02 18:14 UTC, DoomHammer approved these changes

2021-02-02 18:16 UTC, merged